### ISSUE TITLE
Answer with invoice

### ISSUE THREAD

**Issue by prtngn** [rockneurotiko/ex_gram#104]
Hi. How I can send answer via ExGram.Dsl.Answer with included invoice?
And maybe you have good example for invoice and payments process?

**Comment by rockneurotiko** [comment]
You can't use ExGram.Responses.Answer to use the sendInvoice method, there are two ways of doing it:
1) Create a new Response (`ExGram.Responses.SendInvoice`)
2) Manually call `ExGram.send_invoice/7` or `ExGram.send_invoice/8`
