### ISSUE TITLE
Some complex types are incorrect

### ISSUE THREAD

**Issue by a3kov** [rockneurotiko/ex_gram#110]
In the Bot API spec there are types such as "integer or string",  that are treated incorrectly in ex_gram.
Example (chat_id is a string or an integer)
```Elixir
model(
  BotCommandScopeChat,
  [{:type, :string}, {:chat_id, :integer}],
  "Represents the scope of bot commands, covering a specific chat."
)
```
It's probably not an issue for somebody who is only using integers, but if somebody wants to use this spec for parsing the API JSON, it can be a big deal.

**Comment by rockneurotiko** [comment]
🤔  Until now models didn't have union types, so this wasn't contemplated. I'll take a look, thanks for opening the issue!

**Comment by a3kov** [comment]
I've checked, it's mostly about chat_id in different places.

**Comment by rockneurotiko** [comment]
Yeah, I just changed the extractor and re-generated the models on #111 
I'll merge and release soon
