### ISSUE TITLE
What do you think about remove some deps?

### ISSUE THREAD

**Issue by prtngn** [rockneurotiko/ex_gram#144]
Hi. That do you think about remove inch_ex and maxwell adapter.

1. Do you use inch_ex?
2. maxwell adapter last update in 2020 year, and we can't update poison to newest version?

**Comment by rockneurotiko** [comment]
I do agree with removing both, inch has been down for a while, and I don't like not being to update dependencies just because one is not supported anymore.

I just removed them from master, I'll do a release soon
