### ISSUE TITLE
Using answer_callback: any example?

### ISSUE THREAD

**Issue by aus70** [rockneurotiko/ex_gram#158]
Hi

I cannot figure out how to use `answer_callback`: the first argument is the context, but what about the second one? According to the [Telegram docs](https://core.telegram.org/bots/api#callbackquery) the message is optional, but it's not optional in this function.
 
Is there any example I can use?

Thanks!

**Comment by rockneurotiko** [comment]
Yeah, the message is mandatory because we need some of to reply (message, inline, ...) and the DSL takes and message and sets the appropiate id
