### ISSUE TITLE
Tesla configuration too general

### ISSUE THREAD

**Issue by manuel-rubio** [rockneurotiko/ex_gram#167]
If I configure this:

```elixir
config :tesla, adapter: {Tesla.Adapter.Finch, name: ContaBot.Finch}
```

It's ok because it's using `ContaBot.Finch` from the point of view of ExGram, BUT if I add other dependencies that are using another different Tesla adapter by default or even worse, the same Finch but with a different process... it's starting to depend on `ContaBot.Finch` because of the configuration.

Could we change that for:

```elixir
config :ex_gram, tesla_adapter: {Tesla.Adapter.Finch, name: ContaBot.Finch}
```

This way it could be configured inside `ExGram.Adapter.Tesla` using the `adapter` macro and it releases the dependency for the rest of the dependencies also using Tesla.

What do you think?

**Comment by rockneurotiko** [comment]
Yeah, that makes sense, I'll take a look

**Comment by manuel-rubio** [comment]
After checking deeper I could configure it independently so I think it's not needed anymore.
