### ISSUE TITLE
`ExGram` module still uses `Supervisor.Spec`

### ISSUE THREAD

**Issue by indocomsoft** [rockneurotiko/ex_gram#18]
`Supervisor.Spec` is deprecated.

I brought this up recently about the example supervisor, but apparently I missed the one in the `ExGram` module

**Comment by rockneurotiko** [comment]
With https://github.com/rockneurotiko/ex_gram/commit/e697def2d85c289f5dc4c866aa3b384d696a6bb5 it should be removed 100%
