### ISSUE TITLE
Handlers keep retriggering after a couple messages

### ISSUE THREAD

**Issue by alan-andrade** [rockneurotiko/ex_gram#29]
Hi,

I noticed that whenever the bot is in a private chat, after 2 messages ExGram would start to resend the same responses without stopping.

I'm still investigating but wanted raise the issue.

**Comment by rockneurotiko** [comment]
🤔 I don't see that behaviour, not in private chat or nor group chat.

Can you share your bot code, or an extract of your bot code so I can take a look?

**Comment by 97nomad** [comment]
I think that I have the same problem. It looks like ExGram receive the same message multiple times and answer each of them.
Here is my project with this behavior
https://github.com/97nomad/TgScrumPoker

**Comment by rockneurotiko** [comment]
👋 I found the error! 
You can see the fix on #30 
I'll release a patch version later today

**Comment by rockneurotiko** [comment]
Fixed in `0.7.1`

**Comment by rockneurotiko** [comment]
Oh, by the way if you can confirm that it's fixed I would appreciate 😄 

/cc @alan-andrade @97nomad

**Comment by 97nomad** [comment]
Yes, it's all ok now. Thank you ^_^

**Comment by alan-andrade** [comment]
This is working. Thanks a lot @rockneurotiko  !
