### ISSUE TITLE
Fix text matching in the doc

### ISSUE THREAD

**Issue by jean-smaug** [rockneurotiko/ex_gram#46]
Hi

This command does  not match
`{:text, text}` → This tuple will match when plain text is sent to the bot (check privacy mode)

I think it's this definition :)
`{:text, text, message}` → This tuple will match when plain text is sent to the bot (check privacy mode)

**Comment by rockneurotiko** [comment]
Thanks for opening the issue! 

I updated the messages on that part of the README with the current information that can be received.
