### ISSUE TITLE
Release version 0.6.0

### ISSUE THREAD

**Issue by Ironjanowar** [rockneurotiko/ex_gram#5]
Currently version `0.5.0-rc3` is up but the README still says:

![image](https://user-images.githubusercontent.com/9699815/40496643-8cf2533c-5f7a-11e8-96db-bb7cdde29122.png)

So! Time to update :D

**Comment by rockneurotiko** [comment]
So, what we didn't had was a 0.5.0 version, everything was just "release candidate" :joy:

Today I've released the 0.5.0 version, with chil_spec methods
