### ISSUE TITLE
Issue in `send_document` options

### ISSUE THREAD

**Issue by TwistingTwists** [rockneurotiko/ex_gram#65]
Why do we need to add 'file content' ourselves in this file?

`ExGram.send_document(chat_id, {:file_content, "FILE CONTENT", "filename.txt"}) # By content`

I don't understand this function.

**Comment by rockneurotiko** [comment]
That is the way to send any content as any document, basically you are saying "send this file, this is the content, and this is the file name".

If you want to send the file directly from an existing file, you can do it with `{:file, "/full/file/path"}`

Eg:

`ExGram.send_document(chat_id, {:file, "/home/rock/filename.txt"})`
