### ISSUE TITLE
Constructing a new poll

### ISSUE THREAD

**Issue by TwistingTwists** [rockneurotiko/ex_gram#66]
What methods are available for making new `poll` ?

I can see 
```
    model(Poll, [
      {:id, :string},
      {:question, :string},
      {:options, {:array, PollOption}},
      {:total_voter_count, :integer},
      {:is_closed, :boolean},
      {:is_anonymous, :boolean},
      {:type, :string},
      {:allows_multiple_answers, :boolean},
      {:correct_option_id, :integer, :optional},
      {:explanation, :string, :optional},
      {:explanation_entities, {:array, MessageEntity}, :optional},
      {:open_period, :integer, :optional},
      {:close_date, :integer, :optional}
    ])

```

implemented. What's the corresponding function?

**Comment by rockneurotiko** [comment]
👋🏼 

To create a poll you have to use the sendPoll method:

``` elixir

method(
    :post,
    "sendPoll",
    [
      {chat_id, [:integer, :string]},
      {question, [:string]},
      {options, [{:array, :string}]},
      {is_anonymous, [:boolean], :optional},
      {type, [:string], :optional},
      {allows_multiple_answers, [:boolean], :optional},
      {correct_option_id, [:integer], :optional},
      {explanation, [:string], :optional},
      {explanation_parse_mode, [:string], :optional},
      {explanation_entities, [{:array, MessageEntity}], :optional},
      {open_period, [:integer], :optional},
      {close_date, [:integer], :optional},
      {is_closed, [:boolean], :optional},
      {disable_notification, [:boolean], :optional},
      {reply_to_message_id, [:integer], :optional},
      {allow_sending_without_reply, [:boolean], :optional},
      {reply_markup, [InlineKeyboardMarkup, ReplyKeyboardMarkup, ReplyKeyboardRemove, ForceReply],
       :optional}
    ],
    ExGram.Model.Message
  )
```

Something like:

`ExGram.send_poll(chat_id, "Question?", ["Option1", "Option2"])`

**Comment by TwistingTwists** [comment]
Thanks! 

One more question : 
I see `h ExGram.send_poll` in `iex -S mix` 
but cannot find its implementation in the directory. (used Ctrl+F) 

Am I missing something?

**Comment by rockneurotiko** [comment]
You can ask all the questions you want, no problem.

In order to avoid repetition, this library uses scraping + macros to create the basic models and functionality.

In fact, this line creates the method `send_poll` with the parameters needed: https://github.com/rockneurotiko/ex_gram/blob/master/lib/ex_gram.ex#L401

**Comment by TwistingTwists** [comment]
Line Break it was! 

I just skimmed through the `.py` file you use to scrape - Appreciate this approach to avoid repetition ! 

Thank you so much!

**Comment by TwistingTwists** [comment]
`ExGram.send_poll(chat_id, "Question?", ["Option1", "Option2"], [:type, "quiz"])`

this does not work.

How do I specify additional parameters? as maps or as list?

**Comment by rockneurotiko** [comment]
I usually specify them as a keyword list, I think you can use a map too, but as a keyword list is cleaner:

`ExGram.send_poll(chat_id, "Question?", ["Option1", "Option2"], type: "quiz", correct_option_id: 0) # You need to set a correct option for quizes`

**Comment by TwistingTwists** [comment]
This helps! Thanks.
