### ISSUE TITLE
setChatMenuButton error

### ISSUE THREAD

**Issue by prtngn** [rockneurotiko/ex_gram#84]
We have auto generated method:
```
  method(
    :post,
    "setChatMenuButton",
    [{chat_id, [:integer], :optional}, {menu_button, [MenuButton], :optional}],
    true,
    "Use this method to change the bot's menu button in a private chat, or the default menu button. Returns True on success."
  )
```

But menu_button must be MenuButtonCommands, MenuButtonWebApp, MenuButtonDefault.

**Comment by rockneurotiko** [comment]
Oh, you are right, I'll fix it in the next days creating a wrapper struct like ChatMember

**Comment by prtngn** [comment]
Did you forget about this error? )

**Comment by rockneurotiko** [comment]
I totally forgot about it 😂

**Comment by rockneurotiko** [comment]
Can you check the PR #91 ? It adds the generic type MenuButton

**Comment by prtngn** [comment]
I't worked, but there is one problem.
```
ExGram.set_chat_menu_button(chat_id: ..., bot: :..., menu_button: %ExGram.Model.MenuButtonWebApp{type: "web_app", text: "Hello", web_app: %ExGram.Model.WebAppInfo{url: "https://example.com"}})
```

We need to set [type](type: "web_app")

**Comment by rockneurotiko** [comment]
Yeah, that's a problem with the Enum type that I still didn't dedicated too much time to solve 😄
